### PR TITLE
Fix copy reference from source object to new object

### PR DESCRIPTION
**Pull request by splohmer**
Pull request for my created issue (https://github.com/ATM-Consulting/dolibarr_module_productbycompany/issues/7).
It was tested for customer and supplier objects:
customer offer -> order -> invoice, offer direct to invoice
supplier offer -> order -> invoice

### CODE REVIEW

**Comment by atm-john** [comment]
Thanks for your contribution.
Please, If you create a new Pull Reaquest can you update Changelog too ?

**Comment by splohmer** [comment]
Hi,
welcome. Sure I can provide a pull request for the changelog as well. Should the version number 1.1.x also be increased to 1.1.3?

**Comment by splohmer** [comment]
Sorry,
now I got it. I just add it to unreleased. Sorry.

**Comment by splohmer** [comment]
new pull request for changelog added: https://github.com/ATM-Consulting/dolibarr_module_productbycompany/pull/9

**Comment by atm-john** [comment]
For external Pull request it's not a problem if fix is in main branch 
Well done yes it's 1.1.3

**Pull request merged**
